apiVersion: apps/v1
kind: Deployment
metadata:
  name: eco-ci-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eco-ci-app
  template:
    metadata:
      labels:
        app: eco-ci-app
    spec:
      containers:
        - name: eco-ci-app
          image: shreyasia/eco-ci-app:f59015bdc0282e7de078cb50997491e636d2ebd8      
          imagePullPolicy: Never       
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "2.0"
              memory: "256Mi"
            limits:
              cpu: "2.0"
              memory: "256Mi"
